---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: formatting.tex
geometry: margin=1in

title: "CV"
author: Dr Caitlin D. Kuempel
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Lecturer · Griffith University, Brisbane, Australia"
address: "Griffith University, 170 Kessels Rd, Nathan QLD, 4111"
fontawesome: yes
email: c.kuempel@griffith.edu.au
github: cdkuempel
#phone: "+1 555 5555"
#web: 'hrnelson.com'
updated: no

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
# Education

*The University of Queensland*, St. Lucia, QLD, Australia \hfill Nov. 2014- Aug. 2018

> - PhD Conservation Science
> - Thesis title: Evaluating trade-offs between quantitative and qualitative protected area objectives
> - Supervisors: Prof. Hugh Possingham, Prof. Catherine Lovelock and Dr. Alienor Chauvenet

*Northeastern University*, Nahant, MA \hfill Dec. 2013

> - M.S. Marine Biology (emphasis in Coral Reef Ecology (GPA 4.0/4.0))
> - Three Seas Program: 15 months of intensive course and field work in three unique environments 

*University of Iowa*, Iowa City, IA \hfill May 2012

> - B.S. Environmental Biosience (with honors), B.A. French, Certificate in Sustainability

> - Honors in coral morphometrics

# Professional Experience

*Lecturer, Marine Ecological Modelling, Griffith University, Brisbane, Australia* \hfill June 2022-present

*Post-doctoral Fellow, ARC Centre of Excellence for Coral Reef Studies, UQ, Brisbane, Australia* \hfill Feb. 2020-May 2022

> Exploring ways to manage and monitor climate resilient reefs to benefit people and nature as  part of the World Wildlife Fund's Coral Reef Rescue Initiative

*Post-doctoral Fellow, NCEAS, Santa Barbara, CA* \hfill Sept. 2018-Dec. 2019

> Quantified, compared and mapped the production and environmental impacts of all major food systems as  part of a collaborative working group

*Research Assistant, University of Queensland, St. Lucia, QLD, Australia* \hfill June-Sept. 2018

> Developed projects and performed analyses related to international seafood trade.

*Conservation Planning Consultant, IUCN and The University of Queensland* \hfill July-Aug.2018

> Collated data and developed conservation plans for four Pacific Island nations using the spatial conservation planning software, Marxan.

*Research Assistant, The University of Queensland, St. Lucia, QLD, Australia* \hfill Sept. 2017-May 2018

> Updated and built the online presence of the Centre for Biodiversity and 
Conservation Science

*Research Assistant: University of Queensland, St. Lucia, QLD, Australia* \hfill Jan.-March 2017

> Contributed to stakeholder meetings and explored different scheduling scenarios for implementing land-sea spatial conservation plans in Papua New Guinea.

*Volunteer Researcher: University of Queensland and WWF Indonesia* \hfill Sept.-Oct. 2016 

> Led analyses and helped organize workshops to find priority regions for marine conservation in the Sunda Banda Seascape of Indonesia.

*Research Assistant: Smithsonian Tropical Research Institute, Bocas del Toro, Panama* \hfill April-Oct. 2014

> Thalassia testdinum Experimental Network (TEN): investigated the impacts of nutrients and grazer abundance on seagrass across a latitudinal gradient (Florida, Belize, Panama). 

*Conservation Intern: Central Caribbean Marine Institute, Little Cayman, Cayman Islands* \hfill Jan.-April 2014

> Assisted with lionfish management research, coral nursery, and climate data collection. Provided weekly educational talks and tours to guests and tourists. 

*Short-Term Fellow: Smithsonian Tropical Research Institute, Bocas del Toro, Panama* \hfill June-Dec. 2013

> Investigated the role of consumers in coral-algal community dynamics under the
supervision of Dr. Andrew Altieri.

*Research Assistant: University of Iowa Department of Geoscience, Iowa City, IA* \hfill May 2009-2010

> Produced thin-sections of coral specimens and performed morphemetric analysis of the coral species Diploria, resulting in a final honors thesis and research presentation under the supervision of Dr. Ann Budd.

# Grants and Awards

Contributed to the Global Environemntal Facility Coral Reef Rescue awarded to WWF (US$7M) \hfill (2022)

CBCS Small Grants Scheme ($4,500 across three successful proposals) \hfill (2021)

University of Queensland Faculty of Science Awards Rising Star - Academic category Finalist \hfill (Dec. 2020)

APEC Science Prize for Innovation, Research and Education Award - shortlisted for Australian nominee (2020)

University of Queensland Dean's Award for Outstanding HDR Theses (2018)

ARC Laureate Postgraduate Scholarship ($119,376 over 4	years) \hfill Nov 2014-2018

Seafood Footprint Displacement Top-up Scholarship (Dr. Carissa Klein, $5,000) \hfill March-June 2018

50 Reefs Top-up Scholarship ($5,000) \hfill Sept. 2017

University of Queensland Career Development Award ($5,000) \hfill May 2017

Great Barrier Reef Marine Park Authority Science for Management Award ($1,000-declined) \hfill May 2017

Taylor and Francis University of Queensland Library Excellence Award in Research ($1,000) \hfill	May 2017

Australian Coral Reef Society Writing Retreat Scholarship ($500) \hfill May 2016

Smithsonian Tropical Research Institute Short-Term Fellowship ($2,000) \hfill June-Nov. 2013

University of Iowa Old Gold Scholarship ($12,000) \hfill Aug. 2007-May 2011

University of Iowa Athletic Scholarship (Rowing)  \hfill Jan. 2008-May 2011       

# Peer-Reviewed Publications

<!-- > 28. *Kuempel, C.D.*, Frazier, M., Verstaen, J., Rayner, P.E., Blanchard, J.L., Bouwman, L., Cottrell, R.S., Froehlich, H.E., Gephart, J.A., Jacobsen, N.S., McIntyre, P.B., Metian, M., Moran, D., Nash, K.L., Tobben, J., Williams, D.R., Halpern, B.S. (in review). Feed drives land-sea overlap of the global cumulative environmental pressure of farmed chicken and salmon. *Current Biology* -->

> 27. Halpern, B.S., Frazier, M., Verstaen, J., Rayner, P.E., Clawson, S.G., Blanchard, J.L., Cottrell, R.S., Froehlich, H.E., Gephart, J.A., Jacobsen, N.S., *Kuempel, C.D.*, McIntyre, P.B., Metian, M., Moran, D., Nash, K.L., Tobben, J., Williams, D.R. (in review). The cumulative environmental footprint of global food production. *Nature Sustainability*

> 26. Hicks, C.C. Gephart, J.A., Koehn, J.Z., Nakayama, S., Payne, H., Allison, E.H., Delhabib, D., Cao, L., Cohen, P.J., Fanzo, J., Fluet-Chouinard, E., Gelcich, S., Golden, C.D., Gorospe, K.D., Isaacs, M., *Kuempel, C.D.*, Lee, K.N., MacNeil, M.A., Maire, E., Njuki, J., Rao, N., Sumaila, U.R., Selig, E.R., Thilsted, S.H., Wabnitz, C.C.C., Naylor, R.L. (in review). Towards Justice in Blue Food Systems. *Nature Food*

<!-- > 28. Davey, M., *Kuempel, C.D.*, Klein, C.J., Roeflsema, C, Possingham, H.P.(in review). A review of coral reef condition monitoring indicators and their application in spatial conservation planning. *Conservation Biology* -->

<!-- > 25. Klein, C.J., *Kuempel, C.D.*, Watson, R.A., Teneva, L., Coll, M., Mora, C. (in review). Global fishing and seafood trade burdens places with ineffective fisheries management. *Nature Sustainability* -->

<!-- > 22. Froehlich, H.E., Afflerbach, J.C., Williams, D.R., *Kuempel, C.D.*, O'Hara, C., Halpern, B.S. (in review). Integrating aquaculture into sustainable fisheries management. *Proceedings of the National Academy of Sciences* -->

<!-- > 20. Davidson, L.N.K., Brown, C.J., Shumway, N., Holden, M., Jones, K. Klein, C., *Kuempel, C.D.*, Stuart-Smith, R.D., McGowan, J., Possingham, H.P.P., Watson, J.E.M., Dulvy, N.K. (in revision). Gaps in threatened marine species protection inside and beyond MPAs. *Nature Sustainability* -->
> 25. Almaraz, M., *Kuempel, C.D.*, Salter, A., Houlton, B.Z., Halpern, B.S. (2022). The impact of excessive protein consumption on human wastewater nitrogen loading of US waters. *Frontiers in Ecology and the Environment*

> 24. Clawson, S.G., Blasco, G., *Kuempel, C.D.*, Froehlich, H.E., Cottrell, R.S., Metian, M., Tobben, J., Williams, D.R., Nash, K.L., Frazier, M., Verstaen, J., Halpern, B.S. (2022). Mapping the spatial distribution of global mariculture production. *Aquaculture*

> 23. Williams, B.A., Watson, J.E.M., Beyer, H.L., Klein, C.J., Montgomery, J., Runting, R.K., Roberson, L.A., Halpern, B.S., Grantham, H.S., *Kuempel, C.D.*, Frazier, M., Venter, O., Wenger, A. (2021). The global rarity of intact coastal regions. *Conservation Biology*

> 22. *Kuempel, C.D.*, Simmons, B.A., Davey, M.(2022) Assessing he status of existing and tentative marine natural World Heritage areas reveals opportunities to better achieve World Heritage Convention goals. *Journal of Environmental Management*

> 21. *Kuempel, C.D.*, Tulloch, V.J.D., Giffin, A.L., Simmons, B.A., Hagger, V., Phua, C. and Hoegh-Guldberg, O. (2021). Identifying management opportunities to combat climate, land and marine threats across less climate exposed coral reefs. *Conservation Biology*

> 20. Roberson, L., Beyer, H.L., O'Hara, C., Watson, J.E.M., Dunn, Daniel, Klein, C.J., Frazier, M., *Kuempel, C.D.*, Williams, B., Grantham, H., Montgomery, J., Kark, S., Runting, R.K. (2021). Multinational coordination required for conservation of at least 90% of marine species. *Global Change Biology*

> 19. *Kuempel, C.D.*, Chauvenet, A.L.M., Symes, W.S., Possingham, H.P.P. (2021). Predicted protected area downsizing decreases habitat representation across terrestrial ecoregions in the tropics and subtropics. *Conservation Science and Practice*

> 18. Suarez-Castro, A.F., Beyer, H.L., *Kuempel, C.D.*, Linke, S., Borelli, P., Hoegh-Guldberg, O. (2021). Global forest restoration opportunities to foster coral reef conservation. *Global Change Biology*

> 17. Cottrell, R.S., Metian, M., Froehlich, H.E., Blanchard, J.L., Jacobsen, N.S., McIntyre, P.B., Nash, K.L., Williams, D.R., Bouwman, L., Gephart, J.A., *Kuempel, C.D.*, Moran, D.D., Troell, M., Halpern, B.S. (2021) Time to rethink trophic levels in aquaculture policy. *Reviews in Aquaculture*

> 16. *Kuempel, C.D.*, Froehlich, H.E., Halpern, B.S. (2021) An informed though experiment exploring the potential for a paradigm shift in aquatic food production. *Ocean and Coastal Management*

> 15. Adams, V.M., Dimitrova, N., Possingham, H.P., Allan, J.R., *Kuempel, C.D.*, Peterson, N., Kaiye, A. Keako, M., Tulloch, V.J.D. (2021) Scheduling incremental actions to build a comprehensive national protected area netowrk for Papua New Guinea. *Conservation Science and Practice*

> 14. Chauvenet, A.L.M., Watson, J.E.M., Adams, V.M., Di Marco, M., Venter, O., Davis, K.J., Mapping, B., Klein, C.J., *Kuempel, C.D.*, Possingham, H.P. (2020). To achieve big wins for conservation, prioritise protection of ecoregions closest to meeting targets. *One Earth*

> 13.  *Kuempel, C.D.*, Frazier, M., Nash, K.L., Sand Jacobsen, N., Williams, D.R., Blanchard, J.L., Cottrell, R.S., McIntyre, P.B., Moran, D., Bouwman, L., Froehlich, H.E., Gephart, J.A., Metian, M., Tobben, J., Halpern, B.S. (2020). Integrating life-cycle and impact assessments to map food's cumulative environmental footprint. *One Earth*

> 12. Daigle, R., Metaxas, A., Balbar, A., McGowan, J., Treml, E., *Kuempel, C.D.*, Possingham, H., Beger, M. (2020). Operationalizing ecological connectivity to identify spatial conservation priorities with Marxan Connect. *Methods in Ecology and Evolution*, Top cited paper 2022

> 11. *Kuempel, C.D.*, Chauvenet, A.L.M.,  Possingham, H.P., Adams, V.M. (2020). Evidence-based guidelines for prioritizing investments to meet international conservation objectives. *One Earth*

> 10. Halpern, B.S., Blanchard, J.L., Bouwman, L., Cottrell, R.S., Froehlich, H.E., Gephart, J.A., Sand Jacobson, N.,*Kuempel, C.D.*, McIntyre, P.B., Metian,  M., Moran, D., Nash, K.L., Tobben, J., Williams, D.R. (2019). Opinion: Putting all food on the same table: Achieving sustainable food systems requires full accounting. *Proceedings of the National Academy of Sciences*

> 9. *Kuempel, C.D.*, Jones, K.J., Watson J.E.M., Possingham, H.P. (2019). Quantifying biases in placement of marine protected areas relative to abatable biodiversity threats. *Conservation Biology* Top cited paper 2019

> 8. Jantke, K., *Kuempel, C.D.*, McGowan, J.M., Chauvenet, A.L.M., Possingham, H.P. (2018). Metrics for evaluating representation target achievement in protected area networks. *Diversity and Distributions*

> 7. Jones, K.J., Klein, C.J., Halpern, B.S., Venter, O., Grantham, H., *Kuempel, C.D.*, Shumway, N., Friedlander, A.M., Possingham, H.P., Watson, J.E.M. (2018). The location and protection status of Earth’s diminishing marine wilderness. *Current Biology*

> 6. *Kuempel, C.D.* Adams, V.M., Possingham H.P., Bode M. (2018) Bigger or better: the relative benefits of protected area network expansion and enforcement for the conservation of an exploited species. *Conservation Letters*

> 5. Campbell, J.E., Altieri, A.H., Johnston, L., *Kuempel, C.D.*, Paperno, R., Paul, V.J., Duffy, J.E. (2018) Herbivore community determines the magnitude and mechanism of nutrient effects on subtropical and tropical seagrass. *Journal of Ecology*

> 4. Chauvenet, A.L.M., *Kuempel C.D.*, McGowan J., Beger, M., Possingham, H.P. (2017). Methods for calculating Protection Equality for conservation planning. *PloS one*

> 3. *Kuempel, C.D.* and Altieri A. H. (2017). The emergent role of small-bodied herbivores in pre-empting phase shifts on degraded coral reefs. *Scientific Reports*

> 2. *Kuempel, C.D.*, Chauvenet, A.L.M., and Possingham H.P. (2016). Equitable representation of ecoregions is slowly improving despite strategic planning shortfalls. *Conservation Letters*

> 1. Nelson, H.R., *Kuempel, C.D.*, and Altieri, A.H. (2016). The resilience of reef invertebrate biodiversity to coral mortality. *Ecosphere*

# Other Publications

*Kuempel C.D.* and Alyssa Giffin (2021) Resilient reefs, resilient communities: how can we get there? *Catchment to Coast* https://catchmenttocoast.org/2021/12/14/resilient-reefs-and-resilient-communities-how-can-we-get-there/

*Kuempel C.D.*, McGowan J., Estradivari, Handaynai C., Daniel D., Possingham H., Ahmadia, G. (2017) Conservation priority gaps in the Sunda Banda Seascape, Indonesia

*Kuempel C.D.*, Di Marco M., Watson J., Possingham H. (2017). Achieving the targets of global conventions. *Decision Point* http://decision-point.com.au/article/achieving-the-targets-of-global-conventions/

# Presentations

\vspace{-3mm}
*\* oral presentation, $\dagger$ invited presentation*

**Kuempel C**$\dagger$ (2022) Mapping a path for conservation in a developing world. *Griffith University, Brisbane, Australia*

**Kuempel C**$\dagger$ (2022) Conservaiton nature in a developing world. *Linn-Mar High School, Marion, IA, USA*

**Kuempel C** (2021) Informing management across less-climate exposed coral reefs. *International Congress on Conservation Biology*, on-line*

**Kuempel C**$\dagger$ (2021) Coral Reef Rescue Initiative: A climate-centric approach for managing coral reefs for nature and people. *Coral Reef Rehabilitation and Management Program - Coral Triangle Initiative*, on-line*

**Kuempel C**$\dagger$ (2020) The basics of protected area design and evaluation. *University of Queensland Twilight Talk Series*, on-line*

**Kuempel C**$\dagger$ (Nov. 2020) Getting Started with GitHub in R. *Pete Mumby lab group meeting*, UQ*

**Kuempel C**$\dagger$ (Oct. 2020) Workflows and best practices for collaborative coding. *RLadies Brisbane*, online*

**Kuempel C**$\dagger$ (Sept. 2020) Getting Started with GitHub in R. *RLadies Brisbane*, online*

**Kuempel C**$\dagger$ (2020) Coral Reef Rescue Initiative: A climate-centric approach for management coral reefs for nature and people. *Interanational Marine Conservation Congress*, on-line*

**Kuempel C**$\dagger$ (2019) Conserving nature in a developing world. *NCEAS Roundtable*, Santa Barbara, CA,  USA*

**Kuempel C**, Adams V, Possingham H, Bode M (2018) Bigger or better: the relative benefits of MPA expansion and enforcement. *Society for Conservation Biology Oceania Conference*, Wellington, New Zealand*

**Kuempel C**, Jones K, Watson J.E., Possingham H (2018) Global marine protected area establishment largely avoids abatable threats to biodiversity. *International Marine Conservation Congress*, Kuching, Malaysia*

**Kuempel C**$\dagger$ (2018) Evaluating trade-offs between quantitative and qualitative protected area objectives. *Centre for Biodiversity and Conservation Science Seminar*, University of Queensland*

**Kuempel C**, Adams V, Possingham H, Bode M (2017) Bigger or better: the relative benefits of MPA expansion and enforcement. *4th International Marine Protected Areas Congress*. La Serena, Chile*

**Kuempel C**, Jones K, Watson J.E., Possingham H (2017) Are marine protected areas tackling threats? *International Congress on Conservation Biology*, Cartagena, Colombia*

**Kuempel C**, Chauvenet A, Possingham H (2016) Does rapid protected area expansion impact the ecological representation of reserve netwowrks? *Society for Conservation 4th Oceania Congress*, Brisbane, Australia*

**Kuempel C**, Bode M, Adams V, Possingham H (2016) Balancing area and effectiveness: MPA expansion vs. management enforcement in meeting global conservation targets.*International Coral Reef Symposium*, Honolulu, HI*

**Kuempel C**$\dagger$ (2016) Balancing area and effectiveness: Investigating trade-offs in the Convention on Biological Diversity Aichi Target 11. *Environmental Science Seminar*, University of Iowa*

**Kuempel C**, Chauvenet A, Possingham H (2016) Does rapid protected area expansion compromise ecological representation? *Student Conference on Conservation Science*, University of Cambridge, UK

**Kuempel C** and Altieri A (2014) The role of consumers in mediating coral-algal phase shifts. *43rd Annual Benthic Ecology Meeting*, Jacksonville, FL, USA*

# Teaching Experience

ENVM2002/7002 Marine and Coastal Environmental Protection, University of Queensland, \hfill August 2021

> Developed and delivered three lectures and two pratical assessment over three weeks related to anthropogenic impacts on marine and coastal ecosystems. Received teaching evaluation scores of 4.5/5, with feedback that I am "helpful and available to help and deal with my ton of questions".

ENVM3220/7202 Conservation Planning and Management, University of Queensland, \hfill March 2021

> Developed and delivered two lectures and one pratical assessment over two weeks related to spatial planning and project priotisation in a mixed virtual/in-person format. Received teaching evaluation scores of 4.82/5, with two students commenting that I have "clear and detailed explanations" and "am good at explaining things".

WWF Structured Decision Making Training, online, \hfill April-May 2021

> Facilitated a 6-week structured decision making course developed for government and NGO practitions, lead by Queensland Chief Scientist Hugh Possingham

ENVM2002/7002 Marine and Coastal Environmental Protection, University of Queensland, \hfill August 2020

> Developed and delivered a guest lecture on Cumulative Impact Analysis

Software Carpentries Instructor \hfill Sept. 2020

> Certified Software Carpentries Instructor, specialising in introductory to advanced R programming skills and version control (e.g., GitHub). 

CONS7021 Masters conservation decision-making course, University of Queensland \hfill June 2017, 2018

> Lead exercises on the principles and basic use of Marxan spatial conservation palnning software, including giving lectures, overseeing laboratory practicals and grading reports

Moreton Bay Research Station Science Camp, University of Queensland \hfill Oct. 2017-June 2018

> Helped run two-day introductory courese for primary school and international students to explore terrestrial and marine habitats and the flora and fauna of Stradbroke Island

BIOL3000 Third year conservation course, University of Queensland \hfill Aug. 2017

> Facilitated learning exercises on the principles and basic use of Marxan spatial conservation planning software and helped grade reports

Spatial planning and decision-science workshop, Bogota, Colombia \hfill July 2017

> Facilitated a workshop on decision science and practical exercises for using Marxan in spatial conservation planning

Standford University Bing Overseas Program, University of Queensland \hfill Nov. 2017

> Facilitated field exercises on seagrass, dugongs and coral reefs in Moreton Bay for Stanford exchange students and helped design individual research projects

R for beginners, WWF Indonesia Jakarta office \hfill Oct. 2016

> Lead a two day course on the basics of programming in R for conservation practioners

Spatial planning for marine protected area design, Bali, Indonesia \hfill Oct. 2016

> Helped deliver traning materials on using Marxan for spatial planning in Indonesia to government and NGO participants

MARS2005 Australia's Marine Environments second year course, University of Queensland \hfill May 2016

> Led learning exercises centred around the unique ecosystems found on Stradbroke Island, Australia and helped students design, impelment, analyse and report on group research projects

# Service Roles

## **Academic**

Centre for Biodiversity and Conservation Science Management Committee (2021-Present)

> *Early Career Researcher Education Lead*

UNEP MPA Toolbox and Learning Platform

> *Academic Associate, Content editor/coordinator/contributor*

NCEAS Diversity Team representative (2018-2019)

Reviewer for international publications

> *Nature Sustainability, the Journal of Environmental Management, Biological Conservation, Marine Biology, PLoS One, Global Ecology and Conservation, Coral Reefs, Conservation Letters, Conservation Biology, Diversity and Distributions, Marine Policy, Conservation Science and Practice and PeerJ.*

Society for Conservation Biology University of Queensland/Brisbane Chapter

> *Member* (2014-2018) *Board Member/Treasurer* (2015-2017)

Reef Life Survey

> *Survey Volunteer* (2017)

PhD seminar series, The University of Queensland, St. Lucia, QLD, Australia

> *Organiser* (2014-2015)

Queensland Catch a Rising Star Program, Queensland National Science Week

> *Participant* (August 2016) 

## **Community**

RLadies Brisbane - promoting women in programming

> *Organiser/Host* (2020-present)

## **Professional Membership**

Reef Life Survey

Australian Coral Reef Society

Society for Conservation Biology

International Society for Reef Studies

World Commission on Protected Areas Young Professionals Group

## **Working Groups**

**Organiser/Participant** Australia's sustainable seafood future \hfill, UQ Heron Island Research Station, April 2022

**Organiser/Participant** Centre for Biodiversity and Conservation Science HDR/ECR Writing workshop \hfill, Moreton Bay Research Station, Dec. 2021

**Participant** Science for Nature and People Partnership (SNAPP) Coastal Health working group \hfill, NCEAS (on-line), Nov. 2021

**Organiser/Participant** CBCS Integrated Watershed Management Workshop \hfill, University of Queensland, Oct. 2021

**Panel Participant** Working with "big data" in the biological sciences \hfill, University of Queensland, July 2021

**Organiser/Participant** Coral Reef Rescue Initiative Near Real-Time Monitoring Workshop \hfill, WWF online, Sept. 2021

**Participant** Strengthening coastal communities resilience by supporting community enterprises \hfill, WWF online, Oct. 2020

**Participant** What's the catch? Social and environmental sustainability of seafood, Heron Island, University of Queensland \hfill Jan 2021

**Post-doctoral Fellow** Comparing the environmental impacts of global food systems, NCEAS, UC Santa Barbara \hfill Sept. 2018-2020

**Participant** Sustainable seafood and marine conservation, Heron Island, University of Queensland \hfill June 2019

**Participant** Incorporating connectivity into spatial conservation planning,The Nature Conservancy, Washington D.C. \hfill 2017

**Participant/Coordinator** Land-sea conservation planning in Papua New Guinea, Port Moresby, Papua New Guinea \hfill 2017

**Participant/Coordinator** Marine spatial planning in the Sunda Banda Seascape, Bali, Indonesia \hfill 2016

**Organizer/Participant** Global Marine Conservation. Lady Elliot Island, Australia \hfill 2016

# Supervision

Emma Arnett, Master's Student (2020-2021)

> Quantifying like-for-like global seafood trade supervised by Carissa Klein and myself

Ella Sinclair, Volunteer (2020)

> Primary supervisor for conducting literature review of monitoring and evluation indicators for focal WWF Coral Reef Rescue Initiative countries

# Skills

\textit{Programming:} \= R (\textit{advanced}), Matlab (\textit{basic})
\textit{Software:} \= Marxan (\textit{advanced}), Arc/QGIS, Adobe Illustrator, Microsoft Office

