---
output: 
  word_document:
geometry: margin=1in
title: "CV_2page"
author: Dr Caitlin D. Kuempel
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Lecturer · Griffith University, Australia"
#address: "University of Queensland, St. Lucia, QLD, 4072"
fontawesome: yes
email: c.kuempel@griffith.edu.au
github: cdkuempel
#phone: "+1 555 5555"
#web: 'hrnelson.com'
updated: no
keywords: RMarkdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 9 pt
linkcolor: blue
urlcolor: blue
editor_options: 
  markdown: 
    wrap: 72
---

# Education

*The University of Queensland*, PhD Conservation Science, St. Lucia,
QLD, Australia \hfill Nov. 2014- Aug. 2018


*Northeastern University*, M.S. Marine Biology, Nahant, MA \hfill Dec.
2013


*University of Iowa*, B.S. Environmental Biosience (with honors), B.A.
French, Certificate in Sustainability, Honors in coral morphometrics,
Iowa City, IA \hfill May 2012

# Employment history

Lecturer, Marine Ecosystem Modelling, Griffith University, Nathan,
Australia \hfill July 2022-present

Post-doctoral Fellow, ARC Centre of Excellence for Coral Reef Studies,UQ, Brisbane, Australia \hfill Feb. 2020-June 2022

Post-doctoral Fellow, NCEAS, Santa Barbara, CA \hfill Sept. 2018-Dec.
2019

Conservation Planning Consultant, IUCN and The University of
Queensland \hfill July-Aug.2018

Volunteer Researcher: University of Queensland and WWF Indonesia
\hfill Sept.-Oct. 2016

Research Assistant: Smithsonian Tropical Research Institute, Bocas del Toro, Panama \hfill April-Oct. 2014

Conservation Intern: Central Caribbean Marine Institute, Little Cayman, Cayman Islands \hfill Jan.-April 2014

Short-Term Fellow: Smithsonian Tropical Research Institute, Bocas del
Toro, Panama \hfill June-Dec. 2013

Research Assistant: University of Iowa Department of Geoscience, Iowa
City, IA \hfill May 2009-2010

# Positions of leadership

## **Academic**

-   Australian Rivers Institute Early Career Researcher representative
    (2023- present)
-   Griffith Coding Club co-founder and organiser
-   World Wildlife Fund Coral Reef Rescue Initiative Monitoring and Data Management Lead (2020-2022)
-   Centre for Biodiversity and Conservation Science Management
    Committee (2021-2022)
-   NCEAS Diversity Team representative (2018-2019)
-   Reviewer for international publications
-   Society for Conservation Biology University of Queensland/Brisbane
    Chapter (2015-2017)
-   PhD seminar series, The University of Queensland, St. Lucia, QLD,
    Australia (2014-2015)

## **Community**

-   RLadies Brisbane Organising Comittee (2020-present)
-   Software Carpentries instructor
-   UNEP MPA Toolbox and Learning Platform (2021)
-   STEM engagement activities
    -   Brisbane Girls Grammar School Year 9 Geography incursion (2023)
    -   Linn-Mar High School Ventures program mentor (2022-present)
    -   UQ Twilight Talk Series (2020) -Queensland Catch a Rising Star
        Program, Queensland National Science Week (2016)
-   Reef Life Survey Volunteer (2017)

## **Professional Membership**

Reef Life Survey, Australian Marine Sciences Association, Australian
Coral Reef Society, Society for Conservation Biology, International
Society for Reef Studies

# Academic distinctions, prizes, and awards


-   University of Queensland Faculty of Science Awards Rising Star -
    Academic category Finalist \hfill (Dec. 2020)
-   APEC Science Prize for Innovation, Research and Education Award -
    shortlisted for Australian nominee (2020)
-   University of Queensland Dean's Award for Outstanding HDR Theses
    (2018)

# Top 5 publications (h-index 13, Google Scholar) - Griffith Expert, ORCID, Google Scholar

1.  *Kuempel, C.D.*, Frazier, M., Verstaen, J., Rayner, P.E., Blanchard,
    J.L., Bouwman, L., Cottrell, R.S., Froehlich, H.E., Gephart, J.A.,
    Jacobsen, N.S., McIntyre, P.B., Metian, M., Moran, D., Nash, K.L.,
    Tobben, J., Williams, D.R., Halpern, B.S. (2023). Environmental
    footprints of farmed chicken and salmon bridge the land and sea.
    *Current Biology*
2.  Halpern, B.S., Frazier, M., Verstaen, J., Rayner, P.E., Clawson,
    S.G., Blanchard, J.L., Cottrell, R.S., Froehlich, H.E., Gephart,
    J.A., Jacobsen, N.S., *Kuempel, C.D.*, McIntyre, P.B., Metian, M.,
    Moran, D., Nash, K.L., Tobben, J., Williams, D.R. (2022). The
    environmental footprint of global food production. *Nature
    Sustainability*
3.  *Kuempel, C.D.*, Frazier, M., Nash, K.L., Sand Jacobsen, N.,
    Williams, D.R., Blanchard, J.L., Cottrell, R.S., McIntyre, P.B.,
    Moran, D., Bouwman, L., Froehlich, H.E., Gephart, J.A., Metian, M.,
    Tobben, J., Halpern, B.S. (2020). Integrating life-cycle and impact
    assessments to map food's cumulative environmental footprint. *One
    Earth* (12 citations)
4.  *Kuempel, C.D.* Adams, V.M., Possingham H.P., Bode M. (2018) Bigger
    or better: the relative benefits of protected area network expansion
    and enforcement for the conservation of an exploited species.
    *Conservation Letters* (39 citations)
5.  Jones, K.J., Klein, C.J., Halpern, B.S., Venter, O., Grantham, H.,
    *Kuempel, C.D.*, Shumway, N., Friedlander, A.M., Possingham, H.P.,
    Watson, J.E.M. (2018). The location and protection status of Earth's
    diminishing marine wilderness. *Current Biology* (226 citations)

# Other Publications

*Kuempel, C.D.* (2023) Sedimentation sifted out of global pollution
priorities. *Science*

Wakwella, A., Wenger, A., *Kuempel, C.D.*, et al. (2022) Managing
Watersheds for Coral Reefs and Public Health. A Vibrant Oceans
Initiative Whitepaper.


*Kuempel C.D.*, McGowan J., Estradivari, Handaynai C., Daniel D.,
Possingham H., Ahmadia, G. (2017) Conservation priority gaps in the
Sunda Banda Seascape, Indonesia

\newpage

# Grant income
-   CBCS Small Grants Scheme (\$4,500 across three successful proposals)
    \hfill (2021)
    -   ARC Laureate Postgraduate Scholarship (\$119,376 over 4 years)
    \hfill Nov 2014-2018
-   Seafood Footprint Displacement Top-up Scholarship (Dr. Carissa
    Klein, \$5,000) \hfill March-June 2018
-   50 Reefs Top-up Scholarship (\$5,000) \hfill Sept. 2017
-   University of Queensland Career Development Award (\$5,000)
    \hfill May 2017
-   Taylor and Francis University of Queensland Library Excellence Award
    in Research (\$1,000) \hfill  May 2017
-   Smithsonian Tropical Research Institute Short-Term Fellowship
    (\$2,000) \hfill June-Nov. 2013

# Supervision

-   Maria Christofidis, Griffith PhD student (2023-present), Co-primary
    supervisor: Assessing and planning for climate change impacts to
    aquaculture to inform resilient and sustainable expansion
    
-   Alana McPherson, Griffith Honours student (2023-present), Co-primary supervisor: Evaluating marine protected areas

-   Sophie Petrie, Griffith Environmental Science Capstone Project (2023-present), primary
    supervisor. The potential impacts of land-based aquaculture on
    threatened species in Queensland.

-   Emma Arnett, Master's Student (2020-2021), Co-primary supervisor:
    Quantifying redundant global fisheries trade

-   Ella Sinclair, Volunteer (2020): Primary supervisor for conducting
    literature review of monitoring and evluation indicators for focal
    WWF Coral Reef Rescue Initiative countries

# Select general audience publications (links provided)

1. *Kuempel, C.D.* (2023) Farmed salmon or chicken? Environmental footprint
research can guide eco-conscious consumers. [The Conversation](https://theconversation.com/farmed-salmon-or-chicken-environmental-footprint-research-can-guide-eco-conscious-consumers-199773)

2. Almaraz, M. and *Kuempel, C.D.* (2022) The impact of excessive protein consumption on human wastewater nitrogen loading of US waters. [Global Water Forum](https://globalwaterforum.org/2022/08/04/the-impact-of-excessive-protein-consumption-on-human-wastewater-nitrogen-loading-of-us-waters/)

3. *Kuempel, C.D.* and Alyssa Giffin (2021) Resilient reefs, resilient
communities: how can we get there? [Catchment to Coast](https://catchmenttocoast.org/2021/12/14/resilient-reefs-and-resilient-communities-how-can-we-get-there/)

4. Jones, K., Friedlander, A. Halpern, B., *Kuempel, C.D.*, Klein, C.
Grantham, H., Possingham, H., Watson, J., Shumway, N., Venter, O. (2018)
New map shows that only 13% of the oceans are still truly wild. [The
Conversation](https://theconversation.com/new-map-shows-that-only-13-of-the-oceans-are-still-truly-wild-100820#:~:text=Our%20research%2C%20published%20in%20the,human%20activities%20are%20most%20intense.)

5. *Kuempel, C.D.* Southern Coral Sea (2017) [Reef Life Survey blog](https://reeflifesurvey.com/southern-coral-sea/)


# Select media interviews and engagement (links provided)

1. Which food is better for the planet? [The Washington Post](https://www.washingtonpost.com/climate-environment/interactive/2023/food-impact-climate-water-wildlife/)

2. Food for thought: the carbon footprint of salmon and chicken farming mostly stems from feed. [The Guardian](https://www.theguardian.com/environment/2023/feb/13/food-for-thought-carbon-footprint-of-salmon-and-chicken-farming-mostly-stems-from-feed-study-suggests) 

3. To lower food emissions consider what your dinner ate. [Popular Science](https://content.isentia.io/?url=https://www.popsci.com/environment/carbon-emissions-meat-livestock/&key=f50e0409ae20644ddfc8e4da71ba50ad&ver=1&mid=920217296&uid=154795)

4. Farmed chicken and salmon have a global footprint. [Nature](https://www.nature.com/articles/d41586-023-00414-5) 

5. Coming out or not, earthquake aid, and what's the most eco-friendly meat? [Triple J Hack](https://www.abc.net.au/triplej/programs/hack/hack/101960520)

6. Female scientists encouraging children to embrace science [Courier Mail](https://www.couriermail.com.au/news/queensland/bundaberg/female-scientists-encouraging-children-to-embrace-science/news-story/a76c60645f3438df037d12d2f64da262)


# Teaching Experience

I currently convene 3804ENV Marine Ecosystem Modelling and 3606ENV
Conservation Biology at Griffith University and teach into 3033ESC
Environmental Data Analytics.



